import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'core/theme.dart';
import 'core/constants.dart';
import 'ui/screens/auth/splash_screen.dart';
import 'ui/screens/camera/camera_screen.dart';
import 'ui/screens/home/home_screen.dart'; // Import the new Home badge
import 'ui/screens/history/history_screen.dart'; // Import Live History
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:workmanager/workmanager.dart';
import 'workers/sync_worker.dart';
import 'data/local/pending_reading.dart';

void main() async {
  // Ensure flutter gets initialized before running any async platform code.
  WidgetsFlutterBinding.ensureInitialized();

  // Skip Hive initialization on web
  if (!kIsWeb) {
    // Initialize Hive storage for offline capabilities
    await Hive.initFlutter();

    // Wait for the adapter generated by build_runner to be injected over
    Hive.registerAdapter(PendingReadingAdapter());

    // Open the primary box for storing delayed offline meter photos
    await Hive.openBox<PendingReading>(Constants.pendingReadingsBox);

    // Initialize Workmanager for Offline Sync Hooks
    Workmanager().initialize(callbackDispatcher);
  }

  runApp(const ProviderScope(child: WaterMeterApp()));
}

class WaterMeterApp extends StatelessWidget {
  const WaterMeterApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Water Meter App',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system, // Respects device settings
      home: const SplashScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MainScreen extends StatefulWidget {
  const MainScreen({super.key});

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  int _currentIndex = 0;

  // Render Home dynamically mapping to 0
  final List<Widget> _screens = [
    const HomeScreen(),
    const CameraScreen(),
    const HistoryScreen(), // Now links live History Feed
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Water Meter System')),
      body: _screens[_currentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) => setState(() => _currentIndex = index),
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(
            icon: Icon(Icons.camera_alt),
            label: 'Capture',
          ),
          BottomNavigationBarItem(icon: Icon(Icons.history), label: 'History'),
        ],
      ),
    );
  }
}
